a = input('Digite alguma coisa: ')
print(type(a))
print(f'Esta em maiusculo: {a.isupper()}')
print(f'Esta em minusculo: {a.islower()}')
print(f'É alfanumerico: {a.isalnum()}')
print(f'É um numero: {a.isnumeric()}')
print(f'É alfabetico: {a.isalpha()}')
print(f'Esta capitalizada: {a.istitle()}')
